config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'

  resources :products, only:[:index, :show]

  resource :cart, only: [:show, :destroy] do
    post :add, path:'/add/:id'
    get :checkout
  end

  resources :orders, only:[:index, :show, :create]

  namespace :admin do
    resources :products
    resources :orders, except:[:destroy, :new, :create] do
      member do
        put 'pay'
        put 'out'
        put 'deliver'
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items

  def order_number
    "00000000#{id}"
  end

  def state_readable
    case state
    when 'pending'
      '成交'
    when 'paid'
      '已付款'
    when 'out'
      '已出貨'
    when 'deliver'
      '已收貨'
    end
  end

  state_machine :initial => :pending do
    event :pay do
      transition :pending => :paid
    end

    event :out do
      transition :paid => :out
    end

    event :deliver do
      transition :out => :deliver
    end
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :find_order, except: [:index]

  def index
    @orders = Order.all
  end

  def show
  end

  def pay
    if @order.pay
      redirect_to :back, notice: '狀態已變更'
    else
      redirect_to :back, notice: '狀態發生錯誤'
    end
  end

  def out
    if @order.out
      redirect_to :back, notice: '狀態已變更'
    else
      redirect_to :back, notice: '狀態發生錯誤'
    end
  end

  def deliver
    if @order.deliver
      redirect_to :back, notice: '狀態已變更'
    else
      redirect_to :back, notice: '狀態發生錯誤'
    end
  end

  private
  def find_order
    @order = Order.find_by(id: params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :initialize_cart

  def create

    nonce_from_the_client = params[:payment_method_nonce]

    result = Braintree::Transaction.sale(
      :amount => @cart.total_price,
      :payment_method_nonce => nonce_from_the_client
    )

    @order = Order.new(order_params)
    if result
      @cart.items.each do |item|
        @order.order_items.build({product_id: item.id, quantity: item.quantity})
      end
      if @order.save
        # 1. clean cart
        session[:cart] = nil

        # 2. redirect to product page
        redirect_to products_path, notice:'感謝!'
      else
        render 'carts/checkout'
      end
    else
      render 'carts/checkout'
    end
  end

  private
  def order_params
    params.require(:order).permit(:recipient, :address, :tel, :email, :note)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def order_state(order)
    case order.state
    when 'pending'
      '成交'
    when 'paid'
      '已付款'
    when 'out'
      '已出貨'
    when 'deliver'
      '已收貨'
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order_button.html.erb
<% if order.pending? %>
  <%= link_to '付款', pay_admin_order_path(order), method:'put', class:'btn btn-xs btn-danger' %>
<% elsif order.paid? %>
  <%= link_to '出貨', out_admin_order_path(order), method:'put', class:'btn btn-xs btn-danger' %>
<% elsif order.out? %>
  <%= link_to '收貨', deliver_admin_order_path(order), method:'put', class:'btn btn-xs btn-danger' %>
<% end %>

app/views/admin/orders/index.html.erb
<h1>訂單管理</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td>訂單編號</td>
      <td>收件人姓名</td>
      <td>收件人地址</td>
      <td>電話</td>
      <td>Email</td>
      <td>狀態</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.order_number %></td>
      <td><%= order.recipient %></td>
      <td><%= order.address %></td>
      <td><%= order.tel %></td>
      <td><%= order.email %></td>
      <td><%= order.state_readable %></td>
      <td><%= render 'order_button', {order: order} %></td>
    </tr>
  <% end %>
  </tbody>
</table>