config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'

  resources :products, only:[:index, :show]

  resource :cart, only: [:show, :destroy] do
    post :add, path:'/add/:id'
    get :checkout
  end

  resources :orders, only:[:index, :show, :create]

  namespace :admin do
    resources :products
    resources :orders, except:[:destroy, :new, :create] do
      member do
        put 'pay'
        put 'out'
        put 'deliver'
      end
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def self.build_from_hash(hash)
    all_items = []
    unless hash.nil?
      all_items = hash["items"].map { |item| CartItem.new(item["id"], item["quantity"]) }
    end
    new(all_items)
  end

  def serialize
    serialized_items = @items.map { |item| { "id" => item.id , "quantity" => item.quantity } }

    {
      "items" => serialized_items
    }
  end

  def add_item(id)
    item = @items.find { |t| t.id == id }
    if item
      item.quantity += 1
    else
      @items << CartItem.new(id)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.price }

    #total = 0
    #@items.each do |item|
      #total += item.price
    #end
    #return total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_product, only: [:add]
  before_action :initialize_cart

  def add
    @cart.add_item(@product.id)
    session[:cart] = @cart.serialize
    redirect_to :back, notice: "#{@product.name} 已放入購物車"
  end

  def show
  end

  def destroy
    session[:cart] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = Order.new
    @token = Braintree::ClientToken.generate
  end

  private
  def find_product
    @product = Product.find_by(id: params[:id])
    redirect_to root_path if not @product
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_carts.html.erb
<table class="table">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>

  <tbody>
    <% @cart.items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.price %></td>
    </tr>
    <% end %>
  </tbody>

  <tfood>
    <tr>
      <td colspan="3">總計</td>
      <td><%= @cart.total_price %></td>
    </tr>
  </tfood>
</table>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<%= render 'carts' %>

<%= simple_form_for(@order) do |f| %>

  <%= f.input :recipient, label: false, placeholder:'收件人姓名' %>
  <%= f.input :address, label: false, placeholder:'收件人地址'  %>
  <%= f.input :tel, label: false, placeholder:'聯絡電話' %>
  <%= f.input :email, label: false, placeholder:'Email' %>
  <%= f.input :note, label: false, placeholder:'備註' %>

  <hr />
  <div id="payment-form"></div>

  <%= f.submit %>

<% end %>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>
var clientToken = "<%= @token %>";
braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/carts/show.html.erb
<h1>
  購物車
  <%= link_to '清空購物車', cart_path, method: 'delete', data:{ confirm:'你確定嗎?' }, class:'btn btn-xs btn-success' %>
</h1>

<%= render 'carts' %>

<%= link_to '繼續選購', root_path, class:'btn btn-primary' %>
<%= link_to '結帳', checkout_cart_path, class:'btn btn-danger' unless @cart.empty? %>