config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'

  resources :products, only:[:index, :show]

  resource :cart, only: [:show, :destroy] do
    post :add, path:'/add/:id'
    get :checkout
  end

  resources :orders, only:[:index, :show, :create]

  namespace :admin do
    resources :products
    resources :orders, except:[:destroy, :new, :create] do
      member do
        put 'pay'
        put 'out'
        put 'deliver'
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope { where(is_deleted: false) }

  scope :online, -> { where(is_online: true) }

  def destroy
    self.is_deleted = true
    save
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice:'成功新增商品'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path, notice:'成功更新商品'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice:'商品已刪除'
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :is_online, :image)
  end

  def find_product
    @product = Product.find_by(id: params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :initialize_cart

  def index
    @products = Product.online
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :is_online, :image)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :is_online %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>更新商品</h1>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>商品列表</h1>

<%= link_to '新增商品', new_admin_product_path, class:'btn btn-primary' %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Is online</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.is_online %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/products/new.html.erb
<h1>新增商品</h1>

<%= render 'form' %>