config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'

  resources :products, only:[:index, :show]

  resource :cart, only: [:show, :destroy] do
    post :add, path:'/add/:id'
    get :checkout
  end

  resources :orders, only:[:index, :show, :create]

  namespace :admin do
    resources :products
    resources :orders, except:[:destroy, :new, :create] do
      member do
        put 'pay'
        put 'out'
        put 'deliver'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def initialize_cart
    @cart = Cart.build_from_hash(session[:cart])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.erb
<%= link_to cart_path do %>
  購物車
  <% if cart && !cart.empty? %>
   <span class="badge"><%= cart.items.count %></span>
  <% end %>
<% end %>

app/views/application/_flash_message.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= render 'application/cart', {cart: @cart} %></li>
        <li class="dropdown">
        <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to '編輯', edit_user_registration_path %></li>

            <% if current_user.is_admin? %>
            <li><%= link_to '商品管理系統', admin_products_path %></li>
            <li><%= link_to '訂單管理系統', admin_orders_path %></li>
            <% end %>

            <li class="divider"></li>
            <li><%= link_to '登出', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        <% else %>
          <li><%= link_to '註冊', new_user_registration_path %></li>
          <li><%= link_to '登入', new_user_session_path %></li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>